server {
    listen 80;
    server_name dl.who-owns-atlanta.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name dl.who-owns-atlanta.org;

    ssl_certificate     /etc/letsencrypt/live/dl.who-owns-atlanta.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dl.who-owns-atlanta.org/privkey.pem;

    root /var/www/who-owns-atlanta/dl;
    index index.html;

    location / {
        autoindex off;
        try_files $uri $uri/ =404;
    }
}
